// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjX7vlGKCo9ERuAtZTh0_RGn_HaQ5DIm0',
    appId: '1:852057303513:web:51917b7e5aad978c63d1c8',
    messagingSenderId: '852057303513',
    projectId: 'tracking-56310',
    authDomain: 'tracking-56310.firebaseapp.com',
    storageBucket: 'tracking-56310.appspot.com',
    measurementId: 'G-9CXH56CTNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiiMm9ux592frMG0tk_9auQ189PNizN8w',
    appId: '1:852057303513:android:3464bf91f66c8bfa63d1c8',
    messagingSenderId: '852057303513',
    projectId: 'tracking-56310',
    storageBucket: 'tracking-56310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO6_7Sda3TTuhcEVxGL_LgVRZBOhBMUS4',
    appId: '1:852057303513:ios:5c595bb3cf81afb163d1c8',
    messagingSenderId: '852057303513',
    projectId: 'tracking-56310',
    storageBucket: 'tracking-56310.appspot.com',
    iosClientId: '852057303513-jj404b47a0hdb77jouivch35ud7cmg3c.apps.googleusercontent.com',
    iosBundleId: 'com.trackingmap.trakingMap',
  );
}
